name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        if:  "2017-03-08T19:41:26Z" | cut -d T -f 2 | cut -d : -f 1 | == 19
      - name: Print the current date
        run: echo "Done"

