name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Set the value
         id: step_one
         run: |
           echo "action_state=$(echo $(date +'%Y-%m-%dT%H:%M:%S') | cut -d T -f 2 | cut -d : -f 1 | sed 's/^0*//' )"  >> $GITHUB_ENV
           echo $(date +'%Y-%m-%dT%H:%M:%S')
       - name: Use the value to compare
         id: step_two
         if: env.action_state >= 6 &&  env.action_state <= 15
         run: |
           echo "Execute because matches within the interval from 6 to 15"

